apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app.name: hello-world-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30090
      targetPort: 8080
      protocol: TCP
  selector:
    app.name: hello-world-service
